package api

func (s *Server) registerRoutes() {
	// AWS profiles
	s.mux.HandleFunc("GET /api/aws/profiles", s.handleListProfiles)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/identity", s.handleProfileIdentity)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/regions", s.handleRegions)

	// AWS per-profile resources
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/ec2", s.handleEC2)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/rds", s.handleRDS)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/elasticache", s.handleElastiCache)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/lambda", s.handleLambda)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/ecs", s.handleECS)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/ecs/{cluster}/services", s.handleECSServices)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/ecs/{cluster}/tasks", s.handleECSTasks)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/ecs/{cluster}/tasks/{task}/containers", s.handleECSContainers)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/ec2/{instance}/session", s.handleEC2Session)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/ecs/{cluster}/tasks/{task}/exec", s.handleECSExec)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/ecr", s.handleECR)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/ecr/{repo}/images", s.handleECRImages)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/s3", s.handleS3)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/s3/{bucket}/objects", s.handleS3Objects)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/s3/{bucket}/objects/download", s.handleS3ObjectDownload)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/s3/{bucket}/objects/preview", s.handleS3ObjectPreview)
	s.mux.HandleFunc("POST /api/aws/profiles/{profile}/s3/{bucket}/objects/upload", s.handleS3ObjectUpload)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/iam", s.handleIAM)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/sso", s.handleSSO)
	s.mux.HandleFunc("POST /api/aws/profiles/{profile}/sso/login", s.handleSSOLogin)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/ssm/parameters", s.handleSSMList)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/ssm/parameters/{name}", s.handleSSMGet)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/secretsmanager", s.handleSecretsList)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/cfn/stacks", s.handleCFN)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/cfn/stacks/{stack}", s.handleCFNStackDetail)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/cfn/stacks/{stack}/events", s.handleCFNStackEvents)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/cfn/stacks/{stack}/resources", s.handleCFNStackResources)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/kinesis", s.handleKinesis)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/cloudfront", s.handleCloudFront)
	s.mux.HandleFunc("POST /api/aws/profiles/{profile}/cloudfront/{id}/invalidations", s.handleCloudFrontInvalidation)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/elb", s.handleELB)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/elb/listeners", s.handleELBListeners)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/elb/rules", s.handleELBRules)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/elb/target-groups", s.handleELBTargetGroups)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/elb/target-health", s.handleELBTargetHealth)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/dynamo", s.handleDynamo)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/dynamo/{table}/schema", s.handleDynamoSchema)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/dynamo/{table}/items", s.handleDynamoItems)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/apigw", s.handleAPIGW)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/natgw", s.handleNATGW)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/sqs", s.handleSQS)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/waf", s.handleWAF)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/cost", s.handleCost)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/cost/forecast", s.handleCostForecast)

	// Athena (クエリエディタ)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/athena/catalogs", s.handleAthenaCatalogs)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/athena/databases", s.handleAthenaDatabases)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/athena/workgroups", s.handleAthenaWorkgroups)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/athena/tables", s.handleAthenaTables)
	s.mux.HandleFunc("POST /api/aws/profiles/{profile}/athena/query", s.handleAthenaQueryStart)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/athena/query/history", s.handleAthenaQueryHistory)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/athena/query/{id}", s.handleAthenaQueryGet)
	s.mux.HandleFunc("GET /api/aws/profiles/{profile}/athena/query/{id}/results", s.handleAthenaQueryResults)
	s.mux.HandleFunc("DELETE /api/aws/profiles/{profile}/athena/query/{id}", s.handleAthenaQueryStop)

	// BigQuery
	s.mux.HandleFunc("GET /api/bigquery/datasets", s.handleBQDatasets)
	s.mux.HandleFunc("GET /api/bigquery/datasets/{dataset}/tables", s.handleBQTables)
	s.mux.HandleFunc("GET /api/bigquery/datasets/{dataset}/tables/{table}/schema", s.handleBQSchema)
	s.mux.HandleFunc("POST /api/bigquery/query", s.handleBQQueryStart)
	s.mux.HandleFunc("POST /api/bigquery/query/dryrun", s.handleBQQueryDryRun)
	s.mux.HandleFunc("GET /api/bigquery/query/history", s.handleBQQueryHistory)
	s.mux.HandleFunc("GET /api/bigquery/query/jobs/{job}", s.handleBQQueryJob)
	s.mux.HandleFunc("GET /api/bigquery/query/jobs/{job}/results", s.handleBQQueryJobResults)
	s.mux.HandleFunc("DELETE /api/bigquery/query/jobs/{job}", s.handleBQQueryJobCancel)

	// GCP
	s.mux.HandleFunc("GET /api/gcp/projects", s.handleGCPProjects)
	s.mux.HandleFunc("GET /api/gcp/cloudrun", s.handleGCPCloudRun)
	s.mux.HandleFunc("GET /api/gcp/gcs", s.handleGCPGCS)
	s.mux.HandleFunc("GET /api/gcp/gcs/{bucket}/objects", s.handleGCPGCSObjects)
	s.mux.HandleFunc("GET /api/gcp/gcs/{bucket}/objects/download", s.handleGCPGCSObjectDownload)
	s.mux.HandleFunc("GET /api/gcp/gcs/{bucket}/objects/preview", s.handleGCPGCSObjectPreview)
	s.mux.HandleFunc("POST /api/gcp/gcs/{bucket}/objects/upload", s.handleGCPGCSObjectUpload)
	s.mux.HandleFunc("GET /api/gcp/iam", s.handleGCPIAM)
	s.mux.HandleFunc("GET /api/gcp/serviceaccounts", s.handleGCPServiceAccounts)

	// Datadog
	s.mux.HandleFunc("GET /api/datadog/cost/historical", s.handleDatadogHistorical)
	s.mux.HandleFunc("GET /api/datadog/cost/estimated", s.handleDatadogEstimated)

	// TiDB
	s.mux.HandleFunc("GET /api/tidb/projects", s.handleTiDBProjects)
	s.mux.HandleFunc("GET /api/tidb/projects/{project_id}/clusters", s.handleTiDBClusters)
	s.mux.HandleFunc("GET /api/tidb/cost", s.handleTiDBCost)

	// クエリスニペット (サービス別ディレクトリへのローカルファイル保存)
	s.mux.HandleFunc("GET /api/snippets/{service}", s.handleSnippetsList)
	s.mux.HandleFunc("POST /api/snippets/{service}", s.handleSnippetSave)
	s.mux.HandleFunc("DELETE /api/snippets/{service}/{name}", s.handleSnippetDelete)
}
